import { shopConditionLabel } from "@/lib/conditions"

type Tone = "default" | "success" | "warning" | "danger" | "info" | "muted"

const map: Record<string, Tone> = {
  COMPLETED: "success",
  APPROVED: "success",
  RECEIVED: "success",
  INCOMING: "warning",
  COMING: "warning",
  PENDING_APPROVAL: "warning",
  ARRIVED: "success",
  PAID: "success",
  DELIVERED: "success",
  IN_STOCK: "success",
  ACTIVE: "success",
  PENDING: "warning",
  IN_PROGRESS: "warning",
  IN_TRANSIT: "warning",
  WAITING_PARTS: "warning",
  PARTIAL_RECEIVED: "warning",
  ORDERED: "info",
  DIAGNOSING: "info",
  REPAIRING: "info",
  TRANSFERRED: "info",
  CREDIT: "info",
  REJECTED: "danger",
  CANCELLED: "danger",
  REFUNDED: "danger",
  FAULTY: "danger",
  DISPOSED: "danger",
  OVERDUE: "danger",
  SOLD: "muted",
  RETURNED: "warning",
  RETURNED_TO_SUPPLIER: "warning",
  OPEN: "warning",
  SETTLED: "success",
  SWAPPED: "info",
  REPAIRED: "info",
  LOGIN: "info",
  LOGOUT: "muted",
  CREATE: "success",
  UPDATE: "info",
  DELETE: "danger",
  EXPORT: "warning",
  IMPORT: "info",
  DENIED: "danger",
  VIEW: "muted",
  HIGH: "danger",
  MEDIUM: "warning",
  LOW: "muted",
  UNREAD: "warning",
  READ: "muted",
  CASH: "success",
  TRANSFER: "info",
  POS: "info",
  SPLIT_PAYMENT: "info",
}

const labels: Record<string, string> = {
  COMPLETED: "Completed",
  APPROVED: "Approved",
  RECEIVED: "Received",
  INCOMING: "On the way",
  COMING: "On the way",
  PENDING_APPROVAL: "Waiting for yes",
  ARRIVED: "In shop",
  PAID: "Paid",
  DELIVERED: "Delivered",
  IN_STOCK: "In shop",
  ACTIVE: "Open",
  PENDING: "Waiting",
  IN_PROGRESS: "In progress",
  IN_TRANSIT: "On the way",
  WAITING_PARTS: "Waiting for parts",
  PARTIAL_RECEIVED: "Part received",
  ORDERED: "Ordered",
  DIAGNOSING: "Checking",
  REPAIRING: "In repair",
  TRANSFERRED: "Sent to another shop",
  CREDIT: "Credit sales",
  REJECTED: "No",
  CANCELLED: "Cancelled",
  REFUNDED: "Refunded",
  FAULTY: "Damaged",
  DISPOSED: "Written off",
  OVERDUE: "Overdue",
  SOLD: "Sold",
  RETURNED: "Returned",
  RETURNED_TO_SUPPLIER: "Returned to supplier",
  SEND_TO_SUPPLIER: "Send back to supplier",
  SUPPLIER: "Supplier",
  NEIGHBOR: "Neighbor shop",
  TRANSPORT: "Transport",
  FUEL: "Fuel",
  RENT: "Rent",
  UTILITIES: "Light bill",
  REPAIRS: "Repairs",
  SALARY: "Salary",
  MARKETING: "Marketing",
  MISCELLANEOUS: "Other shop bill",
  OPEN: "Open",
  SETTLED: "Settled",
  SWAPPED: "Exchanged",
  REPAIRED: "Repaired",
  BRAND_NEW: "Brand New",
  BRAND_NEW_LOCKED: "Brand New (Locked)",
  BRAND_NEW_NA: "Brand New (N/A)",
  OPEN_BOX: "Open Box",
  OPENBOX: "Open Box",
  UK: "UK",
  UK_USED: "UK",
  UK_LOCKED: "UK (Locked)",
  STANDARD: "Standard",
  NON_ACTIVE: "Non Active",
  REFURBISHED: "Refurbished",
  SWAP_DEVICE: "Swap Deal",
  REPAIR_DEVICE: "Repair device",
  LOGIN: "Sign in",
  LOGOUT: "Sign out",
  CREATE: "Created",
  UPDATE: "Changed",
  DELETE: "Deleted",
  EXPORT: "Downloaded",
  IMPORT: "Uploaded",
  DENIED: "Not allowed",
  VIEW: "Opened",
  APPROVE: "Yes",
  REJECT: "No",
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
  UNREAD: "Unread",
  READ: "Read",
  CASH: "Cash",
  TRANSFER: "Bank",
  POS: "Bank (POS)",
  SPLIT_PAYMENT: "Split payment",
  BANK: "Bank",
  REVERSED: "Reversed",
  WALK_IN: "Walk-in",
  PARKED: "Parked",
  VANISHED: "Vanished",
  POSTED: "Posted",
  SWAP: "Swap Deal",
  EXPENSE: "Expense",
  RECONCILIATION: "Stock count",
  RETURN: "Return",
}

export function statusTone(status: string): Tone {
  return map[status] ?? "muted"
}

export function statusLabel(status: string) {
  return labels[status] ?? status
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")
}

export type BadgeTone = Tone

export function formatCondition(condition?: string | null): string {
  if (!condition) return ""
  return shopConditionLabel(condition) || labels[condition] || statusLabel(condition)
}
