type Tone = "default" | "success" | "warning" | "danger" | "info" | "muted"

const map: Record<string, Tone> = {
  COMPLETED: "success",
  APPROVED: "success",
  RECEIVED: "success",
  INCOMING: "warning",
  COMING: "warning",
  PENDING_APPROVAL: "warning",
  ARRIVED: "success",
  PAID: "success",
  DELIVERED: "success",
  IN_STOCK: "success",
  ACTIVE: "success",
  PENDING: "warning",
  IN_PROGRESS: "warning",
  IN_TRANSIT: "warning",
  WAITING_PARTS: "warning",
  PARTIAL_RECEIVED: "warning",
  ORDERED: "info",
  DIAGNOSING: "info",
  REPAIRING: "info",
  TRANSFERRED: "info",
  CREDIT: "info",
  REJECTED: "danger",
  CANCELLED: "danger",
  REFUNDED: "danger",
  FAULTY: "danger",
  DISPOSED: "danger",
  OVERDUE: "danger",
  SOLD: "muted",
  RETURNED: "warning",
  RETURNED_TO_SUPPLIER: "warning",
  OPEN: "warning",
  SETTLED: "success",
  SWAPPED: "info",
  REPAIRED: "info",
  LOGIN: "info",
  LOGOUT: "muted",
  CREATE: "success",
  UPDATE: "info",
  DELETE: "danger",
  EXPORT: "warning",
  IMPORT: "info",
  DENIED: "danger",
  VIEW: "muted",
  HIGH: "danger",
  MEDIUM: "warning",
  LOW: "muted",
  UNREAD: "warning",
  READ: "muted",
  CASH: "success",
  TRANSFER: "info",
  POS: "info",
  SPLIT_PAYMENT: "info",
}

const labels: Record<string, string> = {
  COMPLETED: "Completed",
  APPROVED: "Approved",
  RECEIVED: "Received",
  INCOMING: "In Transit",
  COMING: "In Transit",
  PENDING_APPROVAL: "Pending Approval",
  ARRIVED: "In Stock",
  PAID: "Paid",
  DELIVERED: "Delivered",
  IN_STOCK: "In Stock",
  ACTIVE: "Active",
  PENDING: "Pending",
  IN_PROGRESS: "In Progress",
  IN_TRANSIT: "In Transit",
  WAITING_PARTS: "Awaiting Parts",
  PARTIAL_RECEIVED: "Partially Received",
  ORDERED: "Ordered",
  DIAGNOSING: "Diagnostics",
  REPAIRING: "In Repair",
  TRANSFERRED: "Transferred",
  CREDIT: "Credit Terms",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
  REFUNDED: "Refunded",
  FAULTY: "Defective",
  DISPOSED: "Written Off",
  OVERDUE: "Overdue",
  SOLD: "Sold",
  RETURNED: "Returned",
  RETURNED_TO_SUPPLIER: "Returned to Vendor (RTV)",
  SEND_TO_SUPPLIER: "Return to Vendor",
  SUPPLIER: "Vendor",
  NEIGHBOR: "External Partner",
  OPEN: "Open",
  SETTLED: "Settled",
  SWAPPED: "Exchanged",
  REPAIRED: "Repaired",
  BRAND_NEW: "Brand New",
  OPEN_BOX: "Open Box",
  UK_USED: "UK Used",
  REFURBISHED: "Refurbished",
  SWAP_DEVICE: "Trade-In",
  REPAIR_DEVICE: "Service Asset",
  LOGIN: "Sign In",
  LOGOUT: "Sign Out",
  CREATE: "Created",
  UPDATE: "Modified",
  DELETE: "Deleted",
  EXPORT: "Exported",
  IMPORT: "Imported",
  DENIED: "Access Denied",
  VIEW: "Accessed",
  APPROVE: "Approved",
  REJECT: "Rejected",
  HIGH: "High Severity",
  MEDIUM: "Medium Severity",
  LOW: "Low Severity",
  UNREAD: "Unread",
  READ: "Read",
  CASH: "Cash",
  TRANSFER: "Bank Transfer",
  POS: "POS Card",
  SPLIT_PAYMENT: "Split Payment",
  REVERSED: "Reversed",
  WALK_IN: "Walk-in Customer",
  PARKED: "On Hold",
  VANISHED: "Purged Draft",
  POSTED: "Committed",
  SWAP: "Trade-In",
  EXPENSE: "Expense",
  RECONCILIATION: "Physical Audit",
  RETURN: "Return",
}

export function statusTone(status: string): Tone {
  return map[status] ?? "muted"
}

export function statusLabel(status: string) {
  return labels[status] ?? status
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ")
}

export type BadgeTone = Tone

export function formatCondition(condition?: string | null): string {
  if (!condition) return ""
  return labels[condition] ?? statusLabel(condition)
}
