import {
  ArrowLeftRight,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  ClipboardCheck,
  Factory,
  GitBranch,
  Handshake,
  LayoutDashboard,
  Package,
  Receipt,
  Repeat2,
  Scale,
  ScanLine,
  ScrollText,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Store,
  TrendingUp,
  Truck,
  Undo2,
  Upload,
  UserRoundCog,
  Users,
  Wallet,
  Wrench,
} from "lucide-react"

export const navGroups = [
  {
    label: "Start",
    items: [
      { name: "Home", href: "/dashboard", icon: LayoutDashboard },
      { name: "How to use this", href: "/help", icon: BookOpen },
    ],
  },
  {
    label: "Stock",
    items: [
      { name: "Upload stock", href: "/uploads", icon: Upload },
      { name: "Phones & items", href: "/products", icon: Smartphone },
      { name: "Phone IMEIs", href: "/imei", icon: ScanLine },
      { name: "Shop stock", href: "/inventory", icon: Boxes },
      { name: "Goods on the way", href: "/incoming", icon: Package },
    ],
  },
  {
    label: "Sell & buy",
    items: [
      { name: "Sales", href: "/sales", icon: ShoppingCart },
      { name: "Sell now", href: "/pos", icon: Store },
      { name: "Close the day", href: "/finance/close", icon: ClipboardCheck },
      { name: "Goods from supplier", href: "/purchases", icon: Truck },
      { name: "Customers", href: "/customers", icon: Users },
      { name: "Suppliers", href: "/suppliers", icon: Factory },
    ],
  },
  {
    label: "Daily work",
    items: [
      { name: "Shop to shop", href: "/transfers", icon: ArrowLeftRight },
      { name: "Neighbor shop fill", href: "/neighbor-fills", icon: Handshake },
      { name: "Returns", href: "/returns", icon: Undo2 },
      { name: "Swaps", href: "/swaps", icon: Repeat2 },
      { name: "Repairs", href: "/repairs", icon: Wrench },
      { name: "Stock count", href: "/reconciliation", icon: ClipboardCheck },
    ],
  },
  {
    label: "Money",
    items: [
      { name: "Revenue & expenditure", href: "/finance", icon: Wallet },
      { name: "Check the books", href: "/audit/books", icon: Scale },
      { name: "Profit", href: "/profits", icon: TrendingUp },
      { name: "Expenses", href: "/expenses", icon: Receipt },
      { name: "Needs approval", href: "/approvals", icon: BadgeCheck },
    ],
  },
  {
    label: "Shop & people",
    items: [
      { name: "Shops", href: "/branches", icon: GitBranch },
      { name: "Staff", href: "/staff", icon: UserRoundCog },
      { name: "Who can see what", href: "/staff/access", icon: Shield },
      { name: "Reports", href: "/reports", icon: BarChart3 },
      { name: "Who did what", href: "/audit", icon: ScrollText },
      { name: "Alerts", href: "/notifications", icon: Bell },
      { name: "Settings", href: "/settings", icon: Settings },
    ],
  },
]
