export const pageTitles: Record<string, string> = {
  "/dashboard": "Home",
  "/uploads": "Upload stock",
  "/uploads/opening-stock": "Opening stock sheet",
  "/uploads/sheets": "Old Excel & CSV sheets",
  "/products": "Phones & items",
  "/products/new": "Add one item",
  "/products/bulk": "Add from a sheet",
  "/products/warranty": "Warranty days",
  "/imei": "Phone numbers (IMEI)",
  "/imei/intake": "Stock intake",
  "/inventory": "Shop stock",
  "/incoming": "Goods on the way",
  "/sales": "Sales",
  "/pos": "Sell now",
  "/purchases": "Goods from supplier",
  "/customers": "Customers",
  "/suppliers": "Suppliers",
  "/transfers": "Shop to shop",
  "/neighbor-fills": "Buy from next door",
  "/profits": "Profit",
  "/returns": "Returns",
  "/swaps": "Swaps",
  "/repairs": "Repairs",
  "/reconciliation": "Stock count",
  "/finance": "Money in & out",
  "/finance/close": "Close the day",
  "/account": "Your login",
  "/help": "How to use this",
  "/expenses": "Expenses",
  "/approvals": "Waiting for yes",
  "/branches": "Shops",
  "/staff": "Staff",
  "/staff/access": "Who can see what",
  "/reports": "Reports",
  "/audit": "Who did what",
  "/audit/books": "Check the books",
  "/notifications": "Alerts",
  "/settings": "Settings",
  "/settings/rules": "Selling rules",
  "/settings/backup": "Backup",
}

export function titleFor(pathname: string) {
  if (pageTitles[pathname]) return pageTitles[pathname]
  const match = Object.keys(pageTitles).find((key) => pathname.startsWith(`${key}/`))
  return match ? pageTitles[match] : "Abu Twins"
}
