export const pageTitles: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/uploads": "Data Import",
  "/uploads/opening-stock": "Opening Stock Sheet",
  "/opening-stock": "Opening Balance Audit",
  "/uploads/sheets": "Legacy Migration",
  "/products": "Product Catalog",
  "/products/new": "New Product Entry",
  "/products/bulk": "Bulk Catalog Ingestion",
  "/products/brands": "Categories & Brands",
  "/products/warranty": "Warranty Policies",
  "/imei": "Serialized Assets (IMEI)",
  "/imei/intake": "Serial Intake",
  "/inventory": "Stock on Hand",
  "/incoming": "Inbound Shipments",
  "/sales": "Sales Orders",
  "/pos": "Point of Sale (POS)",
  "/purchases": "Purchase Orders",
  "/customers": "Customers (CRM)",
  "/suppliers": "Vendors & Suppliers",
  "/transfers": "Stock Transfers",
  "/neighbor-fills": "External Sourcing",
  "/profits": "Profitability (P&L)",
  "/returns": "Customer Returns (RMA)",
  "/swaps": "Trade-In & Exchange",
  "/repairs": "Service & Repairs",
  "/reconciliation": "Inventory Audit",
  "/finance": "Cash Flow & Ledger",
  "/finance/close": "Daily Register Close",
  "/account": "User Account & Security",
  "/help": "Documentation & SOPs",
  "/expenses": "Operating Expenses",
  "/approvals": "Approval Workflows",
  "/branches": "Branch Locations",
  "/staff": "User Management",
  "/staff/access": "Access Control (RBAC)",
  "/reports": "Business Reports",
  "/audit": "Audit Trail",
  "/audit/books": "Financial Audit Pack",
  "/notifications": "System Alerts",
  "/settings": "System Configuration",
  "/settings/rules": "Operational Controls",
  "/settings/backup": "Data Backup",
}

export function titleFor(pathname: string) {
  if (pageTitles[pathname]) return pageTitles[pathname]
  const match = Object.keys(pageTitles).find((key) => pathname.startsWith(`${key}/`))
  return match ? pageTitles[match] : "Abu Twins"
}
