export const pageTitles: Record<string, string> = {
  "/dashboard": "Home",
  "/uploads": "Upload stock",
  "/uploads/opening-stock": "Many at once (Excel)",
  "/opening-stock": "Correct & close opening stock",
  "/uploads/sheets": "Old Excel sheets",
  "/products": "Phones & items",
  "/products/new": "Add one item",
  "/products/bulk": "Add from a sheet",
  "/products/brands": "Brands",
  "/products/warranty": "Warranty days",
  "/imei": "Phone numbers (IMEI)",
  "/imei/intake": "One phone at a time",
  "/inventory": "Shop stock",
  "/incoming": "Goods on the way",
  "/sales": "Sales",
  "/pos": "Sell now",
  "/purchases": "Goods from supplier",
  "/customers": "Customers & money owed",
  "/suppliers": "Suppliers",
  "/transfers": "Shop to shop (Stock Transfer)",
  "/neighbor-fills": "Stock Outsourcing (Neighbour shop fill)",
  "/profits": "Profit",
  "/returns": "Returns",
  "/swaps": "Swap Deal",
  "/repairs": "Repairs",
  "/reconciliation": "Stock count",
  "/finance": "Money in & out",
  "/finance/close": "Close the day",
  "/account": "Your login",
  "/help": "How to use this",
  "/expenses": "Shop expenses",
  "/approvals": "Needs approval",
  "/branches": "Shops",
  "/staff": "Staff",
  "/staff/access": "Who can see what",
  "/reports": "Reports",
  "/audit": "Who did what",
  "/audit/books": "Check the books",
  "/notifications": "Alerts",
  "/settings": "Settings",
  "/settings/rules": "Selling rules",
  "/settings/backup": "Shop backup",
  "/swaps/new": "Start a swap",
  "/returns/new": "Log a return",
  "/repairs/new": "Open a repair",
  "/customers/new": "Add a customer",
  "/suppliers/new": "Add a supplier",
  "/purchases/new": "Book expected goods",
  "/purchases/send-back": "Send back to supplier",
  "/incoming/new": "Book goods coming",
  "/expenses/new": "Ask for a shop bill",
  "/branches/new": "Open a shop",
  "/transfers/new": "Start a transfer",
  "/staff/new": "Add a staff member",
}

export function titleFor(pathname: string) {
  if (pageTitles[pathname]) return pageTitles[pathname]
  const match = Object.keys(pageTitles).find((key) => pathname.startsWith(`${key}/`))
  return match ? pageTitles[match] : "Abu Twins"
}
